[package]
authors = ["unknown <unknown@ad.com>"]
edition = "2018"
name = "archive-cache"
version = "0.1.0"
[dependencies]
lru = "*"
magic = "*"
notify = "4.0.0"
scopeguard = "*"
tree_magic = "*"
zip = "*"

[dependencies.unarr]
path = "/home/comicfans/working/unarr.rs"
